---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: myminseok/java8_git_mvn
    tag: v2

inputs:
- name: source-repo
- name: pipeline-repo
- name: out-repo

outputs:
- name: build-out-repo

params:
  GIT_EMAIL: ((git.email))
  GIT_USERNAME: ((git.username))

run:
  path: /bin/bash
  args:
  - pipeline-repo/ci/tasks/scripts/build-and-test.sh
