---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: myminseok/java8_git_mvn
    tag: v2

inputs:
- name: source-repo
- name: pipeline-repo
- name: release-candidate-dev

outputs:
- name: build-out-repo

run:
  path: /bin/bash
  args:
  - pipeline-repo/ci/tasks/scripts/build-and-test.sh
