---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools

inputs:
- name: out-repo

outputs:
- name: deployed-url-repo

run:
  path: /bin/bash
  args:
  - pipeline-repo/ci/tasks/scripts/deploy.sh
