---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools

inputs:
- name: out-repo
- name: color-info
- name: pipeline-repo

outputs:
- name: output

run:
  path: /bin/bash
  args:
  - pipeline-repo/ci/tasks/scripts/prepare-manifest.sh
