---
platform: linux

image_resource:
  type: docker-image
  source:
    #repository: pivotalservices/docker-concourse-cf-tools
    repository: concourse/buildroot
    tag: "git"

inputs:
- name: pipeline-repo

run:
  path: /bin/bash
  args:
  - pipeline-repo/ci/tasks/scripts/update-deploy-color.sh
