---
groups:
- name: main
  jobs:
  - Build-and-test
  - Deploy-blue
#  - System Test
#  - Rollback

resources:
- name: source-repo
  type: git
  source:
    branch: ((git.source.branch))
    uri: ((git.source.uri))
    private_key: ((git.private_key))
- name: pipeline-repo
  type: git
  source:
    branch: master
    uri: ((git.pipeline.uri))
    private_key: ((git.private_key))
- name: out-repo
  type: git
  source:
    branch: master
    uri: ((git.out.uri))
    private_key: ((git.private_key))

jobs:
- name: Build-and-test
  plan:
  - get: source-repo
    trigger: true
  - get: pipeline-repo
  - get: out-repo
#  - task: task-build
#    file: pipeline-repo/ci/tasks/build-and-test.yml
#    params:
#      GIT_EMAIL: ((git.email))
#      GIT_USERNAME: ((git.username))
#  - put: out-repo
#    params:
#      repository: build-out-repo
#      rebase: true
  - task: task-update-deploy-color
    file: pipeline-repo/ci/tasks/update-deploy-color.yml

- name: Deploy-blue
  plan:
  - get: out-repo
    trigger: true
    passed: [Build-and-test]
